package basketball.stats.enums;

public enum Players {

    ANDERSON_RYAN, AZUBUKKE_KELENNA, BLEDSOE_ERIC, CASSPI_OMRI, DAVIS_ANTHONY, DURANT_KEVIN, GREEN_WILLIE, HAYWARD_GORDON, KNIGHT_BRANDON, MULLENS_BRYEN, MULTIPLE, NONE, OPPONENT, SAMUELS_SAMARDO, TEAM, THABEET_HASHEEM;
}
